### ISSUE TITLE
Erro na construção das Chaves para o SPED

### ISSUE THREAD

**Issue by robmachado** [brazanation/documents#26]
@tonicospinelli 

Vou fazer um pull request para isso, por favor verifique se não usei algo errado.

Estou testando as chaves porém existe um BUG na geração das chaves do SPED.

A chave de 44 dígitos é formada com os seguintes campos:

cUF  OK  (2 dígitos)  total = 2 
AAMM OK (4 dígitos) total = 6
CNPJ OK (14 dígitos) total = 20
modelo OK (2 dígitos) total = 22
serie OK (3 dígitos) total = 25
numero da documento fiscal OK (9 dígitos) total = 34
**tipo de Emissão NOK (1 dígito) total = 34 ???? DEVERIA SER 35**
numero de controle ---- OK (8 dígitos) total = 42 ???? DEVERIA SER 43

ERRO, o campo "tpEmis" não está presente, ele é um inteiro de 1 a 9 indicando emissão normal ou uma das contingências e deve ser passado como parâmetro na função. Com isso o numero formado fica com apenas 42 dígitos e deveria ser de 43 dígitos complementado para 44 pelo digito verificador "cDV".

Tem um outro detalhe que também está errado o numero de controle "cNF" tem apenas 8 dígitos e não 9 como indicado nas classes. A versão que tinha com 9 dígitos é bemmmmm antiga, já faz anos que isso mudou !!

Encontrei outro erro na geração do digito verificador Modulo 11 quando calculo do resto resulta em 0 esta retornando dois dígitos (11) e não deveria !!

**Comment by tonicospinelli** [comment]
@robmachado você consegue me passar um desses números que é gerado com mais de 1 DV?

**Comment by robmachado** [comment]
@tonicospinelli 

Esse por exemplo 5206043300991100250665012000000780206730161**0**

Eu resolvi colocando o $calculator->replaceWhen(0, 11); na linha 160 da classe AbstractAccessKey

Se você coloca o tipo de emissão $emissionMode no código você mesmo irá ver no testes unitários mas esse código causa o erro

$generatedAt = \DateTime::createFromFormat('ymd H:i:s', '060401 00:00:00');
$nfeKey = NFCe::generate(
       52,
        $generatedAt,
        new Cnpj('33009911002506'),
        12,
         780,
         2,
        6730161
 );

Como o modulo do calculo é ZERO ao passar isso para o método  calculateAdditionalDigit($digit) o digito fica sendo igual:
```
$digit = $this->module - $digit;
```
O que resulta em $digit = 11 - 0 = 11 ?!?!? e também pode ocorrer quando o resto for 1 ai o resultado dá 10 ???!!!
