### ISSUE TITLE
Erro no método discoverModule da classe Bahia

### ISSUE THREAD

**Issue by thalfm** [brazanation/documents#36]
Segundo o manual: 
- Para inscrições com 8 dígitos, deve-se calcular com módulo 10, desde que comecem com 0,1,2,3,4,5 e 8.
- Para inscrições com 9 dígitos, deve-se calcular com módulo 10, desde que o segundo dígito seja 0,1,2,3,4,5 e 8.
O módulo 11 esta sendo utilizado para o intervalo de 6 à 9 pegando o 8 o que pode ocasionar erro.

**Comment by tonicospinelli** [comment]
@thalfm consegue mandar a documentação e exemplos?

**Comment by thalfm** [comment]
http://www.sintegra.gov.br/Cad_Estados/cad_BA.html

"1 Cálculo do Dígito Verificador para inscrições estaduais com 8 dígitos:
   1. Para Inscrições cujo primeiro dígito da I.E. é 0,1,2,3,4,5,8 cálculo pelo módulo 10."
...
"2.Para Inscrições cujo primeiro dígito da I.E. é 6, 7 ou 9 cálculo pelo módulo 11."
...
"2 Cálculo do Dígito Verificador para inscrições estaduais com 9 dígitos:
1.Para Inscrições cujo segundo dígito da I.E. é 0,1,2,3,4,5,8 cálculo pelo módulo 10."
...
"2.Para Inscrições cujo segundo dígito da I.E. é 6, 7 ou 9, o cálculo é realizado da mesma forma, entretanto utilizando módulo 11."
