### ISSUE TITLE
Cnpj::createFromString() retornando sempre NULL

### ISSUE THREAD

**Issue by andrekutianski** [brazanation/documents#46]
Ao implementar Cnpj::createFromString() como exemplificado em 

```php
use Brazanation\Documents\Cnpj;

$document = Cnpj::createFromString('99999090910270');

if (false === $document) {
   echo "Not Valid";
}
echo $document; // prints 99999090910270
echo $document->format(); // prints 99.999.090/9102-70
```

`$document` sempre retorna `NULL`

**Comment by tonicospinelli** [comment]
@andrekutianski este CNPJ está sendo validado dentro dos testes. Pode colocar mais informações de como está fazendo os testes para utilizar a biblioteca? Qual a versão do PHP? O máximo de detalhes ajudará a entender o motivo de não funcionar para você.

**Comment by andrekutianski** [comment]
@tonicospinelli sorry, pitfall, falha minha, 96 horas de debug depois de abrir a issue e encontrei o problema. Em uma determinada condição de verificação eu estava comparando com c**p**nj e não c**n**pj. :1st_place_medal: 

:
